/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface GraphComp {
    'data': any;
  }
  interface GraphCompAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }

  interface StickComp {
    'data': any;
  }
  interface StickCompAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GraphComp': Components.GraphComp;
    'StickComp': Components.StickComp;
  }

  interface StencilIntrinsicElements {
    'graph-comp': Components.GraphCompAttributes;
    'stick-comp': Components.StickCompAttributes;
  }


  interface HTMLGraphCompElement extends Components.GraphComp, HTMLStencilElement {}
  var HTMLGraphCompElement: {
    prototype: HTMLGraphCompElement;
    new (): HTMLGraphCompElement;
  };

  interface HTMLStickCompElement extends Components.StickComp, HTMLStencilElement {}
  var HTMLStickCompElement: {
    prototype: HTMLStickCompElement;
    new (): HTMLStickCompElement;
  };

  interface HTMLElementTagNameMap {
    'graph-comp': HTMLGraphCompElement
    'stick-comp': HTMLStickCompElement
  }

  interface ElementTagNameMap {
    'graph-comp': HTMLGraphCompElement;
    'stick-comp': HTMLStickCompElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
